@Resturant.API_HostAddress = https://localhost:7054

GET {{Resturant.API_HostAddress}}/api/weatherforecast

###

GET {{Resturant.API_HostAddress}}/api/weatherforecast

###

@count= 0-1
POST {{Resturant.API_HostAddress}}/api/weatherforecast/generate?count={{count}}
Content-Type: application/json

{
  "min": -23,
  "max": 23
}

###
