name: net workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: list files
        run: ls -la
      - name: run tests
        run: echo "Running tests..."
      - name: run cow
        run: |
          chmod +x script.sh
          ./script.sh
